/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Nexus Calculator API
 * API docs
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateCreatureDto,
  UpdateCreatureDto
} from '.././model';





/**
 * @summary Create a new creature
 */
export const creatureControllerCreate = (
    createCreatureDto: CreateCreatureDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `/creatures`,
      createCreatureDto,options
    );
  }



export const getCreatureControllerCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof creatureControllerCreate>>, TError,{data: CreateCreatureDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof creatureControllerCreate>>, TError,{data: CreateCreatureDto}, TContext> => {

const mutationKey = ['creatureControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof creatureControllerCreate>>, {data: CreateCreatureDto}> = (props) => {
          const {data} = props ?? {};

          return  creatureControllerCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatureControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof creatureControllerCreate>>>
    export type CreatureControllerCreateMutationBody = CreateCreatureDto
    export type CreatureControllerCreateMutationError = AxiosError<unknown>

    /**
 * @summary Create a new creature
 */
export const useCreatureControllerCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof creatureControllerCreate>>, TError,{data: CreateCreatureDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof creatureControllerCreate>>,
        TError,
        {data: CreateCreatureDto},
        TContext
      > => {

      const mutationOptions = getCreatureControllerCreateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Get all creatures
 */
export const creatureControllerFindAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.get(
      `/creatures`,options
    );
  }


export const getCreatureControllerFindAllQueryKey = () => {
    return [`/creatures`] as const;
    }

    
export const getCreatureControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof creatureControllerFindAll>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creatureControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreatureControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof creatureControllerFindAll>>> = ({ signal }) => creatureControllerFindAll({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof creatureControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CreatureControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof creatureControllerFindAll>>>
export type CreatureControllerFindAllQueryError = AxiosError<unknown>


export function useCreatureControllerFindAll<TData = Awaited<ReturnType<typeof creatureControllerFindAll>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof creatureControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof creatureControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof creatureControllerFindAll>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreatureControllerFindAll<TData = Awaited<ReturnType<typeof creatureControllerFindAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creatureControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof creatureControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof creatureControllerFindAll>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreatureControllerFindAll<TData = Awaited<ReturnType<typeof creatureControllerFindAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creatureControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all creatures
 */

export function useCreatureControllerFindAll<TData = Awaited<ReturnType<typeof creatureControllerFindAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creatureControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCreatureControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get a creature by id
 */
export const creatureControllerFindOne = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.get(
      `/creatures/${id}`,options
    );
  }


export const getCreatureControllerFindOneQueryKey = (id: string,) => {
    return [`/creatures/${id}`] as const;
    }

    
export const getCreatureControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof creatureControllerFindOne>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creatureControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreatureControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof creatureControllerFindOne>>> = ({ signal }) => creatureControllerFindOne(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof creatureControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CreatureControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof creatureControllerFindOne>>>
export type CreatureControllerFindOneQueryError = AxiosError<unknown>


export function useCreatureControllerFindOne<TData = Awaited<ReturnType<typeof creatureControllerFindOne>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof creatureControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof creatureControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof creatureControllerFindOne>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreatureControllerFindOne<TData = Awaited<ReturnType<typeof creatureControllerFindOne>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creatureControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof creatureControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof creatureControllerFindOne>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreatureControllerFindOne<TData = Awaited<ReturnType<typeof creatureControllerFindOne>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creatureControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a creature by id
 */

export function useCreatureControllerFindOne<TData = Awaited<ReturnType<typeof creatureControllerFindOne>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creatureControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCreatureControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update a creature by id
 */
export const creatureControllerUpdate = (
    id: string,
    updateCreatureDto: UpdateCreatureDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.patch(
      `/creatures/${id}`,
      updateCreatureDto,options
    );
  }



export const getCreatureControllerUpdateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof creatureControllerUpdate>>, TError,{id: string;data: UpdateCreatureDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof creatureControllerUpdate>>, TError,{id: string;data: UpdateCreatureDto}, TContext> => {

const mutationKey = ['creatureControllerUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof creatureControllerUpdate>>, {id: string;data: UpdateCreatureDto}> = (props) => {
          const {id,data} = props ?? {};

          return  creatureControllerUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatureControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof creatureControllerUpdate>>>
    export type CreatureControllerUpdateMutationBody = UpdateCreatureDto
    export type CreatureControllerUpdateMutationError = AxiosError<unknown>

    /**
 * @summary Update a creature by id
 */
export const useCreatureControllerUpdate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof creatureControllerUpdate>>, TError,{id: string;data: UpdateCreatureDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof creatureControllerUpdate>>,
        TError,
        {id: string;data: UpdateCreatureDto},
        TContext
      > => {

      const mutationOptions = getCreatureControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Delete a creature by id
 */
export const creatureControllerRemove = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/creatures/${id}`,options
    );
  }



export const getCreatureControllerRemoveMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof creatureControllerRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof creatureControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['creatureControllerRemove'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof creatureControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  creatureControllerRemove(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatureControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof creatureControllerRemove>>>
    
    export type CreatureControllerRemoveMutationError = AxiosError<unknown>

    /**
 * @summary Delete a creature by id
 */
export const useCreatureControllerRemove = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof creatureControllerRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof creatureControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getCreatureControllerRemoveMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    