/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Nexus Calculator API
 * API docs
 * OpenAPI spec version: 1.0
 */

export interface CreateCharacterDto {
  path: string;
  subpath?: string;
  name: string;
  vita: number;
  mana: number;
  might: number;
  will: number;
  grace: number;
  alignment: string;
  title?: string;
  clan?: string;
  clantitle?: string;
  imagelocation?: string;
  userId: number;
}
