/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Nexus Calculator API
 * API docs
 * OpenAPI spec version: 1.0
 */

export interface CreateCaveDto {
  cavename: string;
  requirements?: string;
  coordinates?: string;
  boss?: string;
  drops?: string;
}
