/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Nexus Calculator API
 * API docs
 * OpenAPI spec version: 1.0
 */

export interface CreateUserDto {
  email: string;
  name: string;
  password: string;
  /** Optional discriminator, will be generated if not provided */
  discriminator?: string;
}
