/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Nexus Calculator API
 * API docs
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateCharacterDto,
  UpdateCharacterDto
} from '.././model';





/**
 * @summary Create a new character
 */
export const characterControllerCreate = (
    createCharacterDto: CreateCharacterDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `/characters`,
      createCharacterDto,options
    );
  }



export const getCharacterControllerCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof characterControllerCreate>>, TError,{data: CreateCharacterDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof characterControllerCreate>>, TError,{data: CreateCharacterDto}, TContext> => {

const mutationKey = ['characterControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof characterControllerCreate>>, {data: CreateCharacterDto}> = (props) => {
          const {data} = props ?? {};

          return  characterControllerCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CharacterControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof characterControllerCreate>>>
    export type CharacterControllerCreateMutationBody = CreateCharacterDto
    export type CharacterControllerCreateMutationError = AxiosError<unknown>

    /**
 * @summary Create a new character
 */
export const useCharacterControllerCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof characterControllerCreate>>, TError,{data: CreateCharacterDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof characterControllerCreate>>,
        TError,
        {data: CreateCharacterDto},
        TContext
      > => {

      const mutationOptions = getCharacterControllerCreateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Get all characters
 */
export const characterControllerFindAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.get(
      `/characters`,options
    );
  }


export const getCharacterControllerFindAllQueryKey = () => {
    return [`/characters`] as const;
    }

    
export const getCharacterControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof characterControllerFindAll>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof characterControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCharacterControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof characterControllerFindAll>>> = ({ signal }) => characterControllerFindAll({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof characterControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CharacterControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof characterControllerFindAll>>>
export type CharacterControllerFindAllQueryError = AxiosError<unknown>


export function useCharacterControllerFindAll<TData = Awaited<ReturnType<typeof characterControllerFindAll>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof characterControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof characterControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof characterControllerFindAll>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCharacterControllerFindAll<TData = Awaited<ReturnType<typeof characterControllerFindAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof characterControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof characterControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof characterControllerFindAll>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCharacterControllerFindAll<TData = Awaited<ReturnType<typeof characterControllerFindAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof characterControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all characters
 */

export function useCharacterControllerFindAll<TData = Awaited<ReturnType<typeof characterControllerFindAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof characterControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCharacterControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get a character by id
 */
export const characterControllerFindOne = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.get(
      `/characters/${id}`,options
    );
  }


export const getCharacterControllerFindOneQueryKey = (id: string,) => {
    return [`/characters/${id}`] as const;
    }

    
export const getCharacterControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof characterControllerFindOne>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof characterControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCharacterControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof characterControllerFindOne>>> = ({ signal }) => characterControllerFindOne(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof characterControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CharacterControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof characterControllerFindOne>>>
export type CharacterControllerFindOneQueryError = AxiosError<unknown>


export function useCharacterControllerFindOne<TData = Awaited<ReturnType<typeof characterControllerFindOne>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof characterControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof characterControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof characterControllerFindOne>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCharacterControllerFindOne<TData = Awaited<ReturnType<typeof characterControllerFindOne>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof characterControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof characterControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof characterControllerFindOne>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCharacterControllerFindOne<TData = Awaited<ReturnType<typeof characterControllerFindOne>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof characterControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a character by id
 */

export function useCharacterControllerFindOne<TData = Awaited<ReturnType<typeof characterControllerFindOne>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof characterControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCharacterControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update a character by id
 */
export const characterControllerUpdate = (
    id: string,
    updateCharacterDto: UpdateCharacterDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.patch(
      `/characters/${id}`,
      updateCharacterDto,options
    );
  }



export const getCharacterControllerUpdateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof characterControllerUpdate>>, TError,{id: string;data: UpdateCharacterDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof characterControllerUpdate>>, TError,{id: string;data: UpdateCharacterDto}, TContext> => {

const mutationKey = ['characterControllerUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof characterControllerUpdate>>, {id: string;data: UpdateCharacterDto}> = (props) => {
          const {id,data} = props ?? {};

          return  characterControllerUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CharacterControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof characterControllerUpdate>>>
    export type CharacterControllerUpdateMutationBody = UpdateCharacterDto
    export type CharacterControllerUpdateMutationError = AxiosError<unknown>

    /**
 * @summary Update a character by id
 */
export const useCharacterControllerUpdate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof characterControllerUpdate>>, TError,{id: string;data: UpdateCharacterDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof characterControllerUpdate>>,
        TError,
        {id: string;data: UpdateCharacterDto},
        TContext
      > => {

      const mutationOptions = getCharacterControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Delete a character by id
 */
export const characterControllerRemove = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/characters/${id}`,options
    );
  }



export const getCharacterControllerRemoveMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof characterControllerRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof characterControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['characterControllerRemove'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof characterControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  characterControllerRemove(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CharacterControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof characterControllerRemove>>>
    
    export type CharacterControllerRemoveMutationError = AxiosError<unknown>

    /**
 * @summary Delete a character by id
 */
export const useCharacterControllerRemove = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof characterControllerRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof characterControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getCharacterControllerRemoveMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    