/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Nexus Calculator API
 * API docs
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateCaveDto,
  UpdateCaveDto
} from '.././model';





/**
 * @summary Create a new cave
 */
export const caveControllerCreate = (
    createCaveDto: CreateCaveDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `/caves`,
      createCaveDto,options
    );
  }



export const getCaveControllerCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof caveControllerCreate>>, TError,{data: CreateCaveDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof caveControllerCreate>>, TError,{data: CreateCaveDto}, TContext> => {

const mutationKey = ['caveControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof caveControllerCreate>>, {data: CreateCaveDto}> = (props) => {
          const {data} = props ?? {};

          return  caveControllerCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CaveControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof caveControllerCreate>>>
    export type CaveControllerCreateMutationBody = CreateCaveDto
    export type CaveControllerCreateMutationError = AxiosError<unknown>

    /**
 * @summary Create a new cave
 */
export const useCaveControllerCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof caveControllerCreate>>, TError,{data: CreateCaveDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof caveControllerCreate>>,
        TError,
        {data: CreateCaveDto},
        TContext
      > => {

      const mutationOptions = getCaveControllerCreateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Get all caves
 */
export const caveControllerFindAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.get(
      `/caves`,options
    );
  }


export const getCaveControllerFindAllQueryKey = () => {
    return [`/caves`] as const;
    }

    
export const getCaveControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof caveControllerFindAll>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof caveControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCaveControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof caveControllerFindAll>>> = ({ signal }) => caveControllerFindAll({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof caveControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CaveControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof caveControllerFindAll>>>
export type CaveControllerFindAllQueryError = AxiosError<unknown>


export function useCaveControllerFindAll<TData = Awaited<ReturnType<typeof caveControllerFindAll>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof caveControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof caveControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof caveControllerFindAll>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCaveControllerFindAll<TData = Awaited<ReturnType<typeof caveControllerFindAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof caveControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof caveControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof caveControllerFindAll>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCaveControllerFindAll<TData = Awaited<ReturnType<typeof caveControllerFindAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof caveControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all caves
 */

export function useCaveControllerFindAll<TData = Awaited<ReturnType<typeof caveControllerFindAll>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof caveControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCaveControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get a cave by id
 */
export const caveControllerFindOne = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.get(
      `/caves/${id}`,options
    );
  }


export const getCaveControllerFindOneQueryKey = (id: string,) => {
    return [`/caves/${id}`] as const;
    }

    
export const getCaveControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof caveControllerFindOne>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof caveControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCaveControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof caveControllerFindOne>>> = ({ signal }) => caveControllerFindOne(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof caveControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CaveControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof caveControllerFindOne>>>
export type CaveControllerFindOneQueryError = AxiosError<unknown>


export function useCaveControllerFindOne<TData = Awaited<ReturnType<typeof caveControllerFindOne>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof caveControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof caveControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof caveControllerFindOne>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCaveControllerFindOne<TData = Awaited<ReturnType<typeof caveControllerFindOne>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof caveControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof caveControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof caveControllerFindOne>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCaveControllerFindOne<TData = Awaited<ReturnType<typeof caveControllerFindOne>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof caveControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a cave by id
 */

export function useCaveControllerFindOne<TData = Awaited<ReturnType<typeof caveControllerFindOne>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof caveControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCaveControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update a cave by id
 */
export const caveControllerUpdate = (
    id: string,
    updateCaveDto: UpdateCaveDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.patch(
      `/caves/${id}`,
      updateCaveDto,options
    );
  }



export const getCaveControllerUpdateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof caveControllerUpdate>>, TError,{id: string;data: UpdateCaveDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof caveControllerUpdate>>, TError,{id: string;data: UpdateCaveDto}, TContext> => {

const mutationKey = ['caveControllerUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof caveControllerUpdate>>, {id: string;data: UpdateCaveDto}> = (props) => {
          const {id,data} = props ?? {};

          return  caveControllerUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CaveControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof caveControllerUpdate>>>
    export type CaveControllerUpdateMutationBody = UpdateCaveDto
    export type CaveControllerUpdateMutationError = AxiosError<unknown>

    /**
 * @summary Update a cave by id
 */
export const useCaveControllerUpdate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof caveControllerUpdate>>, TError,{id: string;data: UpdateCaveDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof caveControllerUpdate>>,
        TError,
        {id: string;data: UpdateCaveDto},
        TContext
      > => {

      const mutationOptions = getCaveControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Delete a cave by id
 */
export const caveControllerRemove = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/caves/${id}`,options
    );
  }



export const getCaveControllerRemoveMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof caveControllerRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof caveControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['caveControllerRemove'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof caveControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  caveControllerRemove(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CaveControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof caveControllerRemove>>>
    
    export type CaveControllerRemoveMutationError = AxiosError<unknown>

    /**
 * @summary Delete a cave by id
 */
export const useCaveControllerRemove = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof caveControllerRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof caveControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getCaveControllerRemoveMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    